### ISSUE TITLE
Add anti aliasing

### ISSUE THREAD

**Issue by JacksonHoggard** [CremBluRay/voodoo2d#1]
Please replace the TODO comment in Window.java with the following code: 
```java
glfwWindowHint(GLFW_SAMPLES, 4);
```
If you are a beginner, you can start by just adding the above code. If you are maybe a little more experienced, try to add a boolean to allow anti aliasing to be turned on or off (look at how vSync is handled if you are confused on how to do this).

**Comment by Plutone11011** [comment]
Could try to help. Seems like a fun project!
