### ISSUE TITLE
Cannot build SNAPSHOT.jar

### ISSUE THREAD

**Issue by romeojung** [CremBluRay/voodoo2d#21]
**Describe the bug**
I did all the configuration and building steps on the wiki, but the IntelliJ IDEA just gave me a "DEVBUILD.jar", a single jar file, and it wouldn't run because it doesn't have a main class.

**To Reproduce**
1. Clone repo
2. Start IntelliJ IDEA
3. Press green start button on the top menu line of the program right next to the button that says main after editing configuration to build a jar, with the command "clean install" as the wiki suggests
4. Check the target folder

**Expected behavior**
Two .jar files, in which one of them would be named SNAPSHOT.jar, and it would start the engine.

**Screenshots**
![image](https://user-images.githubusercontent.com/32627833/92203082-30586c00-ee35-11ea-9b8a-a4b958e58486.png)
![image](https://user-images.githubusercontent.com/32627833/92203105-3f3f1e80-ee35-11ea-9a96-6ca838fa98c4.png)
![image](https://user-images.githubusercontent.com/32627833/92203112-41a17880-ee35-11ea-85f6-7e31a8243333.png)
![image](https://user-images.githubusercontent.com/32627833/92203347-cc827300-ee35-11ea-857a-8d491a945d41.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK: AdoptOpenJDK11

**Additional context**
As shown in the screenshot, it also opens up the game screen. I'm not sure if that is supposed to happen or not.

**Comment by JacksonHoggard** [comment]
To run a jar file in the command line, you have to type use "java -jar pathtojarfile". It looks like you forgot to add the -jar flag in your command. Also, the game screen is supposed to come up as you've shown in your screenshot.
