### ISSUE TITLE
Windows specific hardcoded paths causes sample game to crush

### ISSUE THREAD

**Issue by merlinDM** [CremBluRay/voodoo2d#22]
**Describe the bug**
Windows specific hardcoded paths causes IO Exceptions during runtime.

1. ```java.io.FileNotFoundException: /path/to/voodoo2d/src\main\resources\maps\example.tmx```
Probable cause is hardcoded path here:
```src/main/java/com/github/crembluray/voodoo2d/game/MapTree.java```
1. ```javax.imageio.IIOException: Can't read input file!```
Probable cause is hardcoded path here:
```src/main/java/com/github/crembluray/voodoo2d/engine/mapping/Layer.java```

Changing the paths helped to run the demo.

**To Reproduce**
1. Use any POSIX OS.
1. Switch to `83c745`.
1. Add Maven exec plugin to pom.xml and specify `com.github.crembluray.voodoo2d.game.Main` as main class:
	```xml
	<plugin>
	    <groupId>org.codehaus.mojo</groupId>
	    <artifactId>exec-maven-plugin</artifactId>
	    <version>1.6.0</version>
	    <configuration>
		<mainClass>com.github.crembluray.voodoo2d.game.Main</mainClass>
	    </configuration>
	</plugin>
	```
1. Run `$ mvn clean install exec:java`

**Expected behavior**
Demo shouldn't crash.

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - JDK: AdoptOpenJDK11

**Comment by JacksonHoggard** [comment]
Thanks for catching this! I've been meaning to change this, I used the hardcoded path for testing and I forgot to remove it. Bad commit practice on my part!
