### ISSUE TITLE
Tile Mapping

### ISSUE THREAD

**Issue by JacksonHoggard** [CremBluRay/voodoo2d#4]
# Add tile mapping into the engine
Edit: thanks @tinovasq for laying the framework for tilemapping! Currently working on creating and combining the layers to be displayed.

### TMX file
```xml
<map version="1.0" orientation="orthogonal" width="20" height="20" tilewidth="32" tileheight="32">
 <tileset firstgid="1" name="grass-tiles-2-small" tilewidth="32" tileheight="32">
  <image source="grass-tiles-2-small.png" width="384" height="192"/>
 </tileset>
 <tileset firstgid="73" name="tree2-final" tilewidth="32" tileheight="32">
  <image source="tree2-final.png" width="256" height="256"/>
 </tileset>
 <layer name="Background" width="20" height="20">
  <data>
   <tile gid="13"/>
   <tile gid="2"/>
   <tile gid="1"/>
   ...
  </data>
 </layer>
 <layer name="Top" width="20" height="20">
  <data>
   <tile gid="0"/>
   ...
  </data>
 </layer>
 <objectgroup name="Collision" width="20" height="20">
  <object x="287" y="354" width="127" height="60"/>
 </objectgroup>
</map>
```
### In the Engine:
![finalimage](https://user-images.githubusercontent.com/22283001/79826232-c5fcce80-8360-11ea-801a-f29c161abdb1.png)
[Helpful link for reading TMX files!](https://gamedevelopment.tutsplus.com/tutorials/parsing-and-rendering-tiled-tmx-format-maps-in-your-own-game-engine--gamedev-3104)

**Comment by tinovasq** [comment]
Good luck! Hopefully my stuff doesn’t break on you! Let me know if you need anything poked at while you work on this.

**Comment by JacksonHoggard** [comment]
Thanks! The code you wrote has worked well so far, haven't had any problems.
